# Example GitHub Actions Workflow for CountyDataSync
# Place this file in .github/workflows/ci-cd.yml in your repository

name: CI/CD - CountyDataSync Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # For scheduled tasks like backups or health checks

jobs:
  build-test-package:
    name: Build, Test, and Package CountyDataSync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install pyinstaller
          pip install python-dotenv

      - name: Generate Application Icon
        run: python generate_icon.py

      - name: Generate Spec File
        run: python generate_spec.py

      - name: Run Unit and Integration Tests
        run: |
          python -m pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Package with PyInstaller
        run: python build_executable.py

      - name: Run ETL with Test Data
        run: |
          # Set environment variables
          echo "USE_TEST_DATA=true" >> $GITHUB_ENV
          python sync.py --test-data

      - name: Run Health Check
        run: python health_check.py

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v3
        with:
          name: county-data-sync-executable
          path: dist/CountyDataSync*
          
      - name: Archive Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/
  
  backup:
    name: Scheduled Database Backup
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run ETL with Test Data
        run: |
          echo "USE_TEST_DATA=true" >> $GITHUB_ENV
          python sync.py --test-data

      - name: Run Backup Script
        run: python backup_script.py

      - name: Upload Backup Artifact
        uses: actions/upload-artifact@v3
        with:
          name: database-backups
          path: backup/

  # Deployment job - uncomment and customize for your deployment
  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: build-test-package
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #     - name: Download Executable Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: county-data-sync-executable
  #         path: executable
  #         
  #     - name: Deploy to Server
  #       env:
  #         DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  #         DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  #         DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #       run: |
  #         # Setup SSH key
  #         mkdir -p ~/.ssh
  #         echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa
  #         
  #         # Deploy using SCP
  #         scp -o StrictHostKeyChecking=no executable/CountyDataSync* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  #         
  #         # Optional: Restart service or perform other post-deployment steps
  #         ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && ./restart_service.sh"